title: My New Blog
author: Ana Vela
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  A simple blog where I will share my adventures with web development.

# social links
twitter_username: anaveecodes # DO NOT include the @ character, or else the build will fail!
github_username:  ana-vela # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
